stages:
  - build
  - deploy

variables:
  IMAGE_NAME: "fsa-frontend"
  INFRA_REPO_NAME: "food-rescue-infrastructure"
  K8S_NAMESPACE: "app"
  K8S_MANIFEST_DIR: "kubernetes/workload/04-app-frontend"
  K8S_DEPLOYMENT_FILE: "kubernetes/workload/04-app-frontend/deployment.yaml"
  DEPLOYMENT_NAME: "fsa-fe"
  DOCKER_DRIVER: overlay2
  DOCKER_HOST: tcp://127.0.0.1:2375
  DOCKER_TLS_VERIFY: ""
  DOCKER_TLS_CERTDIR: ""

build:
  stage: build
  tags:
    - fsa-makarevychv
  image: docker:latest
  services:
    - docker:dind
  before_script:
    - until docker info >/dev/null 2>&1; do sleep 2 && echo "Cakam na Docker daemon..."; done
    - export IMAGE_VERSION="${CI_PIPELINE_ID}-${CI_COMMIT_SHORT_SHA}"
  script:
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin "https://$ACR_REGISTRY"
    - docker build -t "$ACR_REGISTRY/$IMAGE_NAME:$IMAGE_VERSION" -t "$ACR_REGISTRY/$IMAGE_NAME:latest" .
    - docker push "$ACR_REGISTRY/$IMAGE_NAME:$IMAGE_VERSION"
    - docker push "$ACR_REGISTRY/$IMAGE_NAME:latest"
  rules:
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'

deploy:
  stage: deploy
  tags:
    - fsa-makarevychv
  image: alpine/k8s:1.32.3
  before_script:
    - apk add --no-cache git
    - export IMAGE_VERSION="${CI_PIPELINE_ID}-${CI_COMMIT_SHORT_SHA}"
    - mkdir -p ~/.kube
    - echo "$KUBECONFIG_BASE64" | base64 -d > ~/.kube/config
  script:
    - git clone --depth 1 "https://gitlab-ci-token:${CI_JOB_TOKEN}@${CI_SERVER_HOST}/${CI_PROJECT_NAMESPACE}/${INFRA_REPO_NAME}.git" infra
    - sed -i "s|image: .*${IMAGE_NAME}:.*|image: ${ACR_REGISTRY}/${IMAGE_NAME}:${IMAGE_VERSION}|g" "infra/${K8S_DEPLOYMENT_FILE}"
    - kubectl apply -f "infra/${K8S_MANIFEST_DIR}"
    - kubectl rollout status deployment/${DEPLOYMENT_NAME} -n ${K8S_NAMESPACE} --timeout=180s
  rules:
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'
