import {
  faArrowLeft,
  faArrowRight,
  faBagShopping,
  faBell,
  faCalendarDays,
  faChevronRight,
  faCircleCheck,
  faCircleExclamation,
  faCircleInfo,
  faClock,
  faGlobe,
  faHashtag,
  faHeart,
  faLeaf,
  faList,
  faLocationDot,
  faMagnifyingGlass,
  faPen,
  faPhoneVolume,
  faPlus,
  faRotateRight,
  faStar,
  faStore,
  faTrashCan,
  faUser,
  faUserGroup,
  faXmark,
} from '@fortawesome/free-solid-svg-icons';

export const appIcons = {
  arrowLeft: faArrowLeft,
  arrowRight: faArrowRight,
  bagShopping: faBagShopping,
  bell: faBell,
  calendarDays: faCalendarDays,
  chevronRight: faChevronRight,
  circleCheck: faCircleCheck,
  circleExclamation: faCircleExclamation,
  circleInfo: faCircleInfo,
  clock: faClock,
  globe: faGlobe,
  hashtag: faHashtag,
  heart: faHeart,
  leaf: faLeaf,
  list: faList,
  locationDot: faLocationDot,
  magnifyingGlass: faMagnifyingGlass,
  pen: faPen,
  phoneVolume: faPhoneVolume,
  plus: faPlus,
  rotateRight: faRotateRight,
  star: faStar,
  store: faStore,
  trashCan: faTrashCan,
  user: faUser,
  userGroup: faUserGroup,
  xmark: faXmark,
} as const;
