import {
  faArrowLeft,
  faArrowRight,
  faBagShopping,
  faBell,
  faCamera,
  faCalendarDays,
  faCommentDots,
  faChevronRight,
  faCircleCheck,
  faCircleExclamation,
  faCircleInfo,
  faClock,
  faCreditCard,
  faEye,
  faGlobe,
  faHashtag,
  faHeart,
  faImage,
  faLeaf,
  faList,
  faLocationDot,
  faMagnifyingGlass,
  faPaperPlane,
  faPen,
  faPhoneVolume,
  faPlus,
  faQrcode,
  faRotateRight,
  faStar,
  faStore,
  faTrashCan,
  faUpload,
  faUser,
  faUserGroup,
  faWandMagicSparkles,
  faXmark,
} from '@fortawesome/free-solid-svg-icons';

export const appIcons = {
  arrowLeft: faArrowLeft,
  arrowRight: faArrowRight,
  bagShopping: faBagShopping,
  bell: faBell,
  camera: faCamera,
  calendarDays: faCalendarDays,
  commentDots: faCommentDots,
  chevronRight: faChevronRight,
  circleCheck: faCircleCheck,
  circleExclamation: faCircleExclamation,
  circleInfo: faCircleInfo,
  clock: faClock,
  creditCard: faCreditCard,
  eye: faEye,
  globe: faGlobe,
  hashtag: faHashtag,
  heart: faHeart,
  image: faImage,
  leaf: faLeaf,
  list: faList,
  locationDot: faLocationDot,
  magnifyingGlass: faMagnifyingGlass,
  paperPlane: faPaperPlane,
  pen: faPen,
  phoneVolume: faPhoneVolume,
  plus: faPlus,
  qrcode: faQrcode,
  rotateRight: faRotateRight,
  star: faStar,
  store: faStore,
  trashCan: faTrashCan,
  upload: faUpload,
  user: faUser,
  userGroup: faUserGroup,
  wandMagicSparkles: faWandMagicSparkles,
  xmark: faXmark,
} as const;
